ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL PRIVILEGES ON SEQUENCES FROM {{migratorUser}};
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL PRIVILEGES ON TABLES FROM {{migratorUser}};

REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM {{migratorUser}};
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM {{migratorUser}};

REVOKE USAGE, CREATE ON SCHEMA public FROM {{migratorUser}};
