DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = {{baseRoleLiteral}}) THEN
        CREATE ROLE {{baseRole}} NOLOGIN;
    END IF;
END $$;

GRANT USAGE ON SCHEMA public TO {{baseRole}};

GRANT SELECT ON ALL TABLES IN SCHEMA public TO {{baseRole}};
GRANT INSERT ON ALL TABLES IN SCHEMA public TO {{baseRole}};
GRANT UPDATE ON ALL TABLES IN SCHEMA public TO {{baseRole}};
GRANT DELETE ON ALL TABLES IN SCHEMA public TO {{baseRole}};

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO {{baseRole}};

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO {{baseRole}};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT INSERT ON TABLES TO {{baseRole}};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT UPDATE ON TABLES TO {{baseRole}};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT DELETE ON TABLES TO {{baseRole}};

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO {{baseRole}};

GRANT {{baseRole}} TO {{runtimeUser}};
