GRANT USAGE, CREATE ON SCHEMA public TO {{migratorUser}};

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO {{migratorUser}};
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO {{migratorUser}};

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO {{migratorUser}};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO {{migratorUser}};
